// Generated file — do not edit by hand.
//
// Country names in every language the app ships in, taken from CLDR via
// Node's Intl.DisplayNames. Baked in rather than looked up at runtime:
// Hermes' Intl support varies by platform and version, and a picker that
// silently falls back to English on some devices is worse than one that
// never tries.
//
// Regenerate after changing COUNTRY_CALLING_CODES:
//   node scripts/generateCountryNames.mjs
import type { SupportedLanguage } from '../i18n';

const COUNTRY_NAMES: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BY: 'Belarus',
    BE: 'Belgium',
    BA: 'Bosnia & Herzegovina',
    BR: 'Brazil',
    BG: 'Bulgaria',
    CA: 'Canada',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    HR: 'Croatia',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DK: 'Denmark',
    EG: 'Egypt',
    EE: 'Estonia',
    FI: 'Finland',
    FR: 'France',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GR: 'Greece',
    HK: 'Hong Kong SAR China',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IL: 'Israel',
    IT: 'Italy',
    JP: 'Japan',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KW: 'Kuwait',
    LV: 'Latvia',
    LB: 'Lebanon',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MY: 'Malaysia',
    MT: 'Malta',
    MX: 'Mexico',
    MD: 'Moldova',
    MA: 'Morocco',
    NL: 'Netherlands',
    NZ: 'New Zealand',
    NG: 'Nigeria',
    MK: 'North Macedonia',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Philippines',
    PL: 'Poland',
    PT: 'Portugal',
    QA: 'Qatar',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Saudi Arabia',
    RS: 'Serbia',
    SG: 'Singapore',
    SK: 'Slovakia',
    SI: 'Slovenia',
    ZA: 'South Africa',
    KR: 'South Korea',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SE: 'Sweden',
    CH: 'Switzerland',
    TW: 'Taiwan',
    TH: 'Thailand',
    TN: 'Tunisia',
    TR: 'Türkiye',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  tr: {
    AF: 'Afganistan',
    AL: 'Arnavutluk',
    DZ: 'Cezayir',
    AR: 'Arjantin',
    AM: 'Ermenistan',
    AU: 'Avustralya',
    AT: 'Avusturya',
    AZ: 'Azerbaycan',
    BH: 'Bahreyn',
    BD: 'Bangladeş',
    BY: 'Belarus',
    BE: 'Belçika',
    BA: 'Bosna-Hersek',
    BR: 'Brezilya',
    BG: 'Bulgaristan',
    CA: 'Kanada',
    CL: 'Şili',
    CN: 'Çin',
    CO: 'Kolombiya',
    HR: 'Hırvatistan',
    CY: 'Kıbrıs',
    CZ: 'Çekya',
    DK: 'Danimarka',
    EG: 'Mısır',
    EE: 'Estonya',
    FI: 'Finlandiya',
    FR: 'Fransa',
    GE: 'Gürcistan',
    DE: 'Almanya',
    GH: 'Gana',
    GR: 'Yunanistan',
    HK: 'Çin Hong Kong ÖİB',
    HU: 'Macaristan',
    IS: 'İzlanda',
    IN: 'Hindistan',
    ID: 'Endonezya',
    IR: 'İran',
    IQ: 'Irak',
    IE: 'İrlanda',
    IL: 'İsrail',
    IT: 'İtalya',
    JP: 'Japonya',
    JO: 'Ürdün',
    KZ: 'Kazakistan',
    KE: 'Kenya',
    KW: 'Kuveyt',
    LV: 'Letonya',
    LB: 'Lübnan',
    LT: 'Litvanya',
    LU: 'Lüksemburg',
    MY: 'Malezya',
    MT: 'Malta',
    MX: 'Meksika',
    MD: 'Moldova',
    MA: 'Fas',
    NL: 'Hollanda',
    NZ: 'Yeni Zelanda',
    NG: 'Nijerya',
    MK: 'Kuzey Makedonya',
    NO: 'Norveç',
    OM: 'Umman',
    PK: 'Pakistan',
    PH: 'Filipinler',
    PL: 'Polonya',
    PT: 'Portekiz',
    QA: 'Katar',
    RO: 'Romanya',
    RU: 'Rusya',
    SA: 'Suudi Arabistan',
    RS: 'Sırbistan',
    SG: 'Singapur',
    SK: 'Slovakya',
    SI: 'Slovenya',
    ZA: 'Güney Afrika',
    KR: 'Güney Kore',
    ES: 'İspanya',
    LK: 'Sri Lanka',
    SE: 'İsveç',
    CH: 'İsviçre',
    TW: 'Tayvan',
    TH: 'Tayland',
    TN: 'Tunus',
    TR: 'Türkiye',
    UA: 'Ukrayna',
    AE: 'Birleşik Arap Emirlikleri',
    GB: 'Birleşik Krallık',
    US: 'Amerika Birleşik Devletleri',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  pl: {
    AF: 'Afganistan',
    AL: 'Albania',
    DZ: 'Algieria',
    AR: 'Argentyna',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbejdżan',
    BH: 'Bahrajn',
    BD: 'Bangladesz',
    BY: 'Białoruś',
    BE: 'Belgia',
    BA: 'Bośnia i Hercegowina',
    BR: 'Brazylia',
    BG: 'Bułgaria',
    CA: 'Kanada',
    CL: 'Chile',
    CN: 'Chiny',
    CO: 'Kolumbia',
    HR: 'Chorwacja',
    CY: 'Cypr',
    CZ: 'Czechy',
    DK: 'Dania',
    EG: 'Egipt',
    EE: 'Estonia',
    FI: 'Finlandia',
    FR: 'Francja',
    GE: 'Gruzja',
    DE: 'Niemcy',
    GH: 'Ghana',
    GR: 'Grecja',
    HK: 'SRA Hongkong (Chiny)',
    HU: 'Węgry',
    IS: 'Islandia',
    IN: 'Indie',
    ID: 'Indonezja',
    IR: 'Iran',
    IQ: 'Irak',
    IE: 'Irlandia',
    IL: 'Izrael',
    IT: 'Włochy',
    JP: 'Japonia',
    JO: 'Jordania',
    KZ: 'Kazachstan',
    KE: 'Kenia',
    KW: 'Kuwejt',
    LV: 'Łotwa',
    LB: 'Liban',
    LT: 'Litwa',
    LU: 'Luksemburg',
    MY: 'Malezja',
    MT: 'Malta',
    MX: 'Meksyk',
    MD: 'Mołdawia',
    MA: 'Maroko',
    NL: 'Holandia',
    NZ: 'Nowa Zelandia',
    NG: 'Nigeria',
    MK: 'Macedonia Północna',
    NO: 'Norwegia',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Filipiny',
    PL: 'Polska',
    PT: 'Portugalia',
    QA: 'Katar',
    RO: 'Rumunia',
    RU: 'Rosja',
    SA: 'Arabia Saudyjska',
    RS: 'Serbia',
    SG: 'Singapur',
    SK: 'Słowacja',
    SI: 'Słowenia',
    ZA: 'Republika Południowej Afryki',
    KR: 'Korea Południowa',
    ES: 'Hiszpania',
    LK: 'Sri Lanka',
    SE: 'Szwecja',
    CH: 'Szwajcaria',
    TW: 'Tajwan',
    TH: 'Tajlandia',
    TN: 'Tunezja',
    TR: 'Turcja',
    UA: 'Ukraina',
    AE: 'Zjednoczone Emiraty Arabskie',
    GB: 'Wielka Brytania',
    US: 'Stany Zjednoczone',
    UY: 'Urugwaj',
    VE: 'Wenezuela',
    VN: 'Wietnam',
  },
  es: {
    AF: 'Afganistán',
    AL: 'Albania',
    DZ: 'Argelia',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaiyán',
    BH: 'Baréin',
    BD: 'Bangladés',
    BY: 'Bielorrusia',
    BE: 'Bélgica',
    BA: 'Bosnia y Herzegovina',
    BR: 'Brasil',
    BG: 'Bulgaria',
    CA: 'Canadá',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    HR: 'Croacia',
    CY: 'Chipre',
    CZ: 'Chequia',
    DK: 'Dinamarca',
    EG: 'Egipto',
    EE: 'Estonia',
    FI: 'Finlandia',
    FR: 'Francia',
    GE: 'Georgia',
    DE: 'Alemania',
    GH: 'Ghana',
    GR: 'Grecia',
    HK: 'RAE de Hong Kong (China)',
    HU: 'Hungría',
    IS: 'Islandia',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Irán',
    IQ: 'Irak',
    IE: 'Irlanda',
    IL: 'Israel',
    IT: 'Italia',
    JP: 'Japón',
    JO: 'Jordania',
    KZ: 'Kazajistán',
    KE: 'Kenia',
    KW: 'Kuwait',
    LV: 'Letonia',
    LB: 'Líbano',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    MY: 'Malasia',
    MT: 'Malta',
    MX: 'México',
    MD: 'Moldavia',
    MA: 'Marruecos',
    NL: 'Países Bajos',
    NZ: 'Nueva Zelanda',
    NG: 'Nigeria',
    MK: 'Macedonia del Norte',
    NO: 'Noruega',
    OM: 'Omán',
    PK: 'Pakistán',
    PH: 'Filipinas',
    PL: 'Polonia',
    PT: 'Portugal',
    QA: 'Catar',
    RO: 'Rumanía',
    RU: 'Rusia',
    SA: 'Arabia Saudí',
    RS: 'Serbia',
    SG: 'Singapur',
    SK: 'Eslovaquia',
    SI: 'Eslovenia',
    ZA: 'Sudáfrica',
    KR: 'Corea del Sur',
    ES: 'España',
    LK: 'Sri Lanka',
    SE: 'Suecia',
    CH: 'Suiza',
    TW: 'Taiwán',
    TH: 'Tailandia',
    TN: 'Túnez',
    TR: 'Turquía',
    UA: 'Ucrania',
    AE: 'Emiratos Árabes Unidos',
    GB: 'Reino Unido',
    US: 'Estados Unidos',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  fr: {
    AF: 'Afghanistan',
    AL: 'Albanie',
    DZ: 'Algérie',
    AR: 'Argentine',
    AM: 'Arménie',
    AU: 'Australie',
    AT: 'Autriche',
    AZ: 'Azerbaïdjan',
    BH: 'Bahreïn',
    BD: 'Bangladesh',
    BY: 'Biélorussie',
    BE: 'Belgique',
    BA: 'Bosnie-Herzégovine',
    BR: 'Brésil',
    BG: 'Bulgarie',
    CA: 'Canada',
    CL: 'Chili',
    CN: 'Chine',
    CO: 'Colombie',
    HR: 'Croatie',
    CY: 'Chypre',
    CZ: 'Tchéquie',
    DK: 'Danemark',
    EG: 'Égypte',
    EE: 'Estonie',
    FI: 'Finlande',
    FR: 'France',
    GE: 'Géorgie',
    DE: 'Allemagne',
    GH: 'Ghana',
    GR: 'Grèce',
    HK: 'R.A.S. chinoise de Hong Kong',
    HU: 'Hongrie',
    IS: 'Islande',
    IN: 'Inde',
    ID: 'Indonésie',
    IR: 'Iran',
    IQ: 'Irak',
    IE: 'Irlande',
    IL: 'Israël',
    IT: 'Italie',
    JP: 'Japon',
    JO: 'Jordanie',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KW: 'Koweït',
    LV: 'Lettonie',
    LB: 'Liban',
    LT: 'Lituanie',
    LU: 'Luxembourg',
    MY: 'Malaisie',
    MT: 'Malte',
    MX: 'Mexique',
    MD: 'Moldavie',
    MA: 'Maroc',
    NL: 'Pays-Bas',
    NZ: 'Nouvelle-Zélande',
    NG: 'Nigeria',
    MK: 'Macédoine du Nord',
    NO: 'Norvège',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Philippines',
    PL: 'Pologne',
    PT: 'Portugal',
    QA: 'Qatar',
    RO: 'Roumanie',
    RU: 'Russie',
    SA: 'Arabie saoudite',
    RS: 'Serbie',
    SG: 'Singapour',
    SK: 'Slovaquie',
    SI: 'Slovénie',
    ZA: 'Afrique du Sud',
    KR: 'Corée du Sud',
    ES: 'Espagne',
    LK: 'Sri Lanka',
    SE: 'Suède',
    CH: 'Suisse',
    TW: 'Taïwan',
    TH: 'Thaïlande',
    TN: 'Tunisie',
    TR: 'Turquie',
    UA: 'Ukraine',
    AE: 'Émirats arabes unis',
    GB: 'Royaume-Uni',
    US: 'États-Unis',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Viêt Nam',
  },
  it: {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaigian',
    BH: 'Bahrein',
    BD: 'Bangladesh',
    BY: 'Bielorussia',
    BE: 'Belgio',
    BA: 'Bosnia ed Erzegovina',
    BR: 'Brasile',
    BG: 'Bulgaria',
    CA: 'Canada',
    CL: 'Cile',
    CN: 'Cina',
    CO: 'Colombia',
    HR: 'Croazia',
    CY: 'Cipro',
    CZ: 'Cechia',
    DK: 'Danimarca',
    EG: 'Egitto',
    EE: 'Estonia',
    FI: 'Finlandia',
    FR: 'Francia',
    GE: 'Georgia',
    DE: 'Germania',
    GH: 'Ghana',
    GR: 'Grecia',
    HK: 'RAS di Hong Kong',
    HU: 'Ungheria',
    IS: 'Islanda',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Irlanda',
    IL: 'Israele',
    IT: 'Italia',
    JP: 'Giappone',
    JO: 'Giordania',
    KZ: 'Kazakistan',
    KE: 'Kenya',
    KW: 'Kuwait',
    LV: 'Lettonia',
    LB: 'Libano',
    LT: 'Lituania',
    LU: 'Lussemburgo',
    MY: 'Malaysia',
    MT: 'Malta',
    MX: 'Messico',
    MD: 'Moldavia',
    MA: 'Marocco',
    NL: 'Paesi Bassi',
    NZ: 'Nuova Zelanda',
    NG: 'Nigeria',
    MK: 'Macedonia del Nord',
    NO: 'Norvegia',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Filippine',
    PL: 'Polonia',
    PT: 'Portogallo',
    QA: 'Qatar',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Arabia Saudita',
    RS: 'Serbia',
    SG: 'Singapore',
    SK: 'Slovacchia',
    SI: 'Slovenia',
    ZA: 'Sudafrica',
    KR: 'Corea del Sud',
    ES: 'Spagna',
    LK: 'Sri Lanka',
    SE: 'Svezia',
    CH: 'Svizzera',
    TW: 'Taiwan',
    TH: 'Thailandia',
    TN: 'Tunisia',
    TR: 'Turchia',
    UA: 'Ucraina',
    AE: 'Emirati Arabi Uniti',
    GB: 'Regno Unito',
    US: 'Stati Uniti',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  de: {
    AF: 'Afghanistan',
    AL: 'Albanien',
    DZ: 'Algerien',
    AR: 'Argentinien',
    AM: 'Armenien',
    AU: 'Australien',
    AT: 'Österreich',
    AZ: 'Aserbaidschan',
    BH: 'Bahrain',
    BD: 'Bangladesch',
    BY: 'Belarus',
    BE: 'Belgien',
    BA: 'Bosnien und Herzegowina',
    BR: 'Brasilien',
    BG: 'Bulgarien',
    CA: 'Kanada',
    CL: 'Chile',
    CN: 'China',
    CO: 'Kolumbien',
    HR: 'Kroatien',
    CY: 'Zypern',
    CZ: 'Tschechien',
    DK: 'Dänemark',
    EG: 'Ägypten',
    EE: 'Estland',
    FI: 'Finnland',
    FR: 'Frankreich',
    GE: 'Georgien',
    DE: 'Deutschland',
    GH: 'Ghana',
    GR: 'Griechenland',
    HK: 'Sonderverwaltungsregion Hongkong',
    HU: 'Ungarn',
    IS: 'Island',
    IN: 'Indien',
    ID: 'Indonesien',
    IR: 'Iran',
    IQ: 'Irak',
    IE: 'Irland',
    IL: 'Israel',
    IT: 'Italien',
    JP: 'Japan',
    JO: 'Jordanien',
    KZ: 'Kasachstan',
    KE: 'Kenia',
    KW: 'Kuwait',
    LV: 'Lettland',
    LB: 'Libanon',
    LT: 'Litauen',
    LU: 'Luxemburg',
    MY: 'Malaysia',
    MT: 'Malta',
    MX: 'Mexiko',
    MD: 'Republik Moldau',
    MA: 'Marokko',
    NL: 'Niederlande',
    NZ: 'Neuseeland',
    NG: 'Nigeria',
    MK: 'Nordmazedonien',
    NO: 'Norwegen',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Philippinen',
    PL: 'Polen',
    PT: 'Portugal',
    QA: 'Katar',
    RO: 'Rumänien',
    RU: 'Russland',
    SA: 'Saudi-Arabien',
    RS: 'Serbien',
    SG: 'Singapur',
    SK: 'Slowakei',
    SI: 'Slowenien',
    ZA: 'Südafrika',
    KR: 'Südkorea',
    ES: 'Spanien',
    LK: 'Sri Lanka',
    SE: 'Schweden',
    CH: 'Schweiz',
    TW: 'Taiwan',
    TH: 'Thailand',
    TN: 'Tunesien',
    TR: 'Türkei',
    UA: 'Ukraine',
    AE: 'Vereinigte Arabische Emirate',
    GB: 'Vereinigtes Königreich',
    US: 'Vereinigte Staaten',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  ja: {
    AF: 'アフガニスタン',
    AL: 'アルバニア',
    DZ: 'アルジェリア',
    AR: 'アルゼンチン',
    AM: 'アルメニア',
    AU: 'オーストラリア',
    AT: 'オーストリア',
    AZ: 'アゼルバイジャン',
    BH: 'バーレーン',
    BD: 'バングラデシュ',
    BY: 'ベラルーシ',
    BE: 'ベルギー',
    BA: 'ボスニア・ヘルツェゴビナ',
    BR: 'ブラジル',
    BG: 'ブルガリア',
    CA: 'カナダ',
    CL: 'チリ',
    CN: '中国',
    CO: 'コロンビア',
    HR: 'クロアチア',
    CY: 'キプロス',
    CZ: 'チェコ',
    DK: 'デンマーク',
    EG: 'エジプト',
    EE: 'エストニア',
    FI: 'フィンランド',
    FR: 'フランス',
    GE: 'ジョージア',
    DE: 'ドイツ',
    GH: 'ガーナ',
    GR: 'ギリシャ',
    HK: '中華人民共和国香港特別行政区',
    HU: 'ハンガリー',
    IS: 'アイスランド',
    IN: 'インド',
    ID: 'インドネシア',
    IR: 'イラン',
    IQ: 'イラク',
    IE: 'アイルランド',
    IL: 'イスラエル',
    IT: 'イタリア',
    JP: '日本',
    JO: 'ヨルダン',
    KZ: 'カザフスタン',
    KE: 'ケニア',
    KW: 'クウェート',
    LV: 'ラトビア',
    LB: 'レバノン',
    LT: 'リトアニア',
    LU: 'ルクセンブルク',
    MY: 'マレーシア',
    MT: 'マルタ',
    MX: 'メキシコ',
    MD: 'モルドバ',
    MA: 'モロッコ',
    NL: 'オランダ',
    NZ: 'ニュージーランド',
    NG: 'ナイジェリア',
    MK: '北マケドニア',
    NO: 'ノルウェー',
    OM: 'オマーン',
    PK: 'パキスタン',
    PH: 'フィリピン',
    PL: 'ポーランド',
    PT: 'ポルトガル',
    QA: 'カタール',
    RO: 'ルーマニア',
    RU: 'ロシア',
    SA: 'サウジアラビア',
    RS: 'セルビア',
    SG: 'シンガポール',
    SK: 'スロバキア',
    SI: 'スロベニア',
    ZA: '南アフリカ',
    KR: '韓国',
    ES: 'スペイン',
    LK: 'スリランカ',
    SE: 'スウェーデン',
    CH: 'スイス',
    TW: '台湾',
    TH: 'タイ',
    TN: 'チュニジア',
    TR: 'トルコ',
    UA: 'ウクライナ',
    AE: 'アラブ首長国連邦',
    GB: 'イギリス',
    US: 'アメリカ合衆国',
    UY: 'ウルグアイ',
    VE: 'ベネズエラ',
    VN: 'ベトナム',
  },
  'zh-Hans': {
    AF: '阿富汗',
    AL: '阿尔巴尼亚',
    DZ: '阿尔及利亚',
    AR: '阿根廷',
    AM: '亚美尼亚',
    AU: '澳大利亚',
    AT: '奥地利',
    AZ: '阿塞拜疆',
    BH: '巴林',
    BD: '孟加拉国',
    BY: '白俄罗斯',
    BE: '比利时',
    BA: '波斯尼亚和黑塞哥维那',
    BR: '巴西',
    BG: '保加利亚',
    CA: '加拿大',
    CL: '智利',
    CN: '中国',
    CO: '哥伦比亚',
    HR: '克罗地亚',
    CY: '塞浦路斯',
    CZ: '捷克',
    DK: '丹麦',
    EG: '埃及',
    EE: '爱沙尼亚',
    FI: '芬兰',
    FR: '法国',
    GE: '格鲁吉亚',
    DE: '德国',
    GH: '加纳',
    GR: '希腊',
    HK: '中国香港特别行政区',
    HU: '匈牙利',
    IS: '冰岛',
    IN: '印度',
    ID: '印度尼西亚',
    IR: '伊朗',
    IQ: '伊拉克',
    IE: '爱尔兰',
    IL: '以色列',
    IT: '意大利',
    JP: '日本',
    JO: '约旦',
    KZ: '哈萨克斯坦',
    KE: '肯尼亚',
    KW: '科威特',
    LV: '拉脱维亚',
    LB: '黎巴嫩',
    LT: '立陶宛',
    LU: '卢森堡',
    MY: '马来西亚',
    MT: '马耳他',
    MX: '墨西哥',
    MD: '摩尔多瓦',
    MA: '摩洛哥',
    NL: '荷兰',
    NZ: '新西兰',
    NG: '尼日利亚',
    MK: '北马其顿',
    NO: '挪威',
    OM: '阿曼',
    PK: '巴基斯坦',
    PH: '菲律宾',
    PL: '波兰',
    PT: '葡萄牙',
    QA: '卡塔尔',
    RO: '罗马尼亚',
    RU: '俄罗斯',
    SA: '沙特阿拉伯',
    RS: '塞尔维亚',
    SG: '新加坡',
    SK: '斯洛伐克',
    SI: '斯洛文尼亚',
    ZA: '南非',
    KR: '韩国',
    ES: '西班牙',
    LK: '斯里兰卡',
    SE: '瑞典',
    CH: '瑞士',
    TW: '台湾',
    TH: '泰国',
    TN: '突尼斯',
    TR: '土耳其',
    UA: '乌克兰',
    AE: '阿拉伯联合酋长国',
    GB: '英国',
    US: '美国',
    UY: '乌拉圭',
    VE: '委内瑞拉',
    VN: '越南',
  },
  'zh-Hant': {
    AF: '阿富汗',
    AL: '阿爾巴尼亞',
    DZ: '阿爾及利亞',
    AR: '阿根廷',
    AM: '亞美尼亞',
    AU: '澳洲',
    AT: '奧地利',
    AZ: '亞塞拜然',
    BH: '巴林',
    BD: '孟加拉',
    BY: '白俄羅斯',
    BE: '比利時',
    BA: '波士尼亞與赫塞哥維納',
    BR: '巴西',
    BG: '保加利亞',
    CA: '加拿大',
    CL: '智利',
    CN: '中國',
    CO: '哥倫比亞',
    HR: '克羅埃西亞',
    CY: '賽普勒斯',
    CZ: '捷克',
    DK: '丹麥',
    EG: '埃及',
    EE: '愛沙尼亞',
    FI: '芬蘭',
    FR: '法國',
    GE: '喬治亞',
    DE: '德國',
    GH: '迦納',
    GR: '希臘',
    HK: '中國香港特別行政區',
    HU: '匈牙利',
    IS: '冰島',
    IN: '印度',
    ID: '印尼',
    IR: '伊朗',
    IQ: '伊拉克',
    IE: '愛爾蘭',
    IL: '以色列',
    IT: '義大利',
    JP: '日本',
    JO: '約旦',
    KZ: '哈薩克',
    KE: '肯亞',
    KW: '科威特',
    LV: '拉脫維亞',
    LB: '黎巴嫩',
    LT: '立陶宛',
    LU: '盧森堡',
    MY: '馬來西亞',
    MT: '馬爾他',
    MX: '墨西哥',
    MD: '摩爾多瓦',
    MA: '摩洛哥',
    NL: '荷蘭',
    NZ: '紐西蘭',
    NG: '奈及利亞',
    MK: '北馬其頓',
    NO: '挪威',
    OM: '阿曼',
    PK: '巴基斯坦',
    PH: '菲律賓',
    PL: '波蘭',
    PT: '葡萄牙',
    QA: '卡達',
    RO: '羅馬尼亞',
    RU: '俄羅斯',
    SA: '沙烏地阿拉伯',
    RS: '塞爾維亞',
    SG: '新加坡',
    SK: '斯洛伐克',
    SI: '斯洛維尼亞',
    ZA: '南非',
    KR: '南韓',
    ES: '西班牙',
    LK: '斯里蘭卡',
    SE: '瑞典',
    CH: '瑞士',
    TW: '台灣',
    TH: '泰國',
    TN: '突尼西亞',
    TR: '土耳其',
    UA: '烏克蘭',
    AE: '阿拉伯聯合大公國',
    GB: '英國',
    US: '美國',
    UY: '烏拉圭',
    VE: '委內瑞拉',
    VN: '越南',
  },
};

/** The country's name in the given language, falling back to whatever the
 * calling-code table carries (English) for anything unlisted. */
export function localizedCountryName(iso2: string, language: string, fallback: string): string {
  const forLanguage = COUNTRY_NAMES[language as SupportedLanguage];
  return forLanguage?.[iso2] ?? fallback;
}
