// Generated file — do not edit by hand.
//
// Country names in every language the app ships in, taken from CLDR via
// Node's Intl.DisplayNames. Baked in rather than looked up at runtime:
// Hermes' Intl support varies by platform and version, and a picker that
// silently falls back to English on some devices is worse than one that
// never tries.
//
// Regenerate after changing COUNTRY_CALLING_CODES:
//   node scripts/generateCountryNames.mjs
import type { SupportedLanguage } from '../i18n';

const COUNTRY_NAMES: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BY: 'Belarus',
    BE: 'Belgium',
    BA: 'Bosnia & Herzegovina',
    BR: 'Brazil',
    BG: 'Bulgaria',
    CA: 'Canada',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    HR: 'Croatia',
    CY: 'Cyprus',
    CZ: 'Czechia',
    DK: 'Denmark',
    EG: 'Egypt',
    EE: 'Estonia',
    FI: 'Finland',
    FR: 'France',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GR: 'Greece',
    HK: 'Hong Kong SAR China',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IL: 'Israel',
    IT: 'Italy',
    JP: 'Japan',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KW: 'Kuwait',
    LV: 'Latvia',
    LB: 'Lebanon',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MY: 'Malaysia',
    MT: 'Malta',
    MX: 'Mexico',
    MD: 'Moldova',
    MA: 'Morocco',
    NL: 'Netherlands',
    NZ: 'New Zealand',
    NG: 'Nigeria',
    MK: 'North Macedonia',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Philippines',
    PL: 'Poland',
    PT: 'Portugal',
    QA: 'Qatar',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Saudi Arabia',
    RS: 'Serbia',
    SG: 'Singapore',
    SK: 'Slovakia',
    SI: 'Slovenia',
    ZA: 'South Africa',
    KR: 'South Korea',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SE: 'Sweden',
    CH: 'Switzerland',
    TW: 'Taiwan',
    TH: 'Thailand',
    TN: 'Tunisia',
    TR: 'Türkiye',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  tr: {
    AF: 'Afganistan',
    AL: 'Arnavutluk',
    DZ: 'Cezayir',
    AR: 'Arjantin',
    AM: 'Ermenistan',
    AU: 'Avustralya',
    AT: 'Avusturya',
    AZ: 'Azerbaycan',
    BH: 'Bahreyn',
    BD: 'Bangladeş',
    BY: 'Belarus',
    BE: 'Belçika',
    BA: 'Bosna-Hersek',
    BR: 'Brezilya',
    BG: 'Bulgaristan',
    CA: 'Kanada',
    CL: 'Şili',
    CN: 'Çin',
    CO: 'Kolombiya',
    HR: 'Hırvatistan',
    CY: 'Kıbrıs',
    CZ: 'Çekya',
    DK: 'Danimarka',
    EG: 'Mısır',
    EE: 'Estonya',
    FI: 'Finlandiya',
    FR: 'Fransa',
    GE: 'Gürcistan',
    DE: 'Almanya',
    GH: 'Gana',
    GR: 'Yunanistan',
    HK: 'Çin Hong Kong ÖİB',
    HU: 'Macaristan',
    IS: 'İzlanda',
    IN: 'Hindistan',
    ID: 'Endonezya',
    IR: 'İran',
    IQ: 'Irak',
    IE: 'İrlanda',
    IL: 'İsrail',
    IT: 'İtalya',
    JP: 'Japonya',
    JO: 'Ürdün',
    KZ: 'Kazakistan',
    KE: 'Kenya',
    KW: 'Kuveyt',
    LV: 'Letonya',
    LB: 'Lübnan',
    LT: 'Litvanya',
    LU: 'Lüksemburg',
    MY: 'Malezya',
    MT: 'Malta',
    MX: 'Meksika',
    MD: 'Moldova',
    MA: 'Fas',
    NL: 'Hollanda',
    NZ: 'Yeni Zelanda',
    NG: 'Nijerya',
    MK: 'Kuzey Makedonya',
    NO: 'Norveç',
    OM: 'Umman',
    PK: 'Pakistan',
    PH: 'Filipinler',
    PL: 'Polonya',
    PT: 'Portekiz',
    QA: 'Katar',
    RO: 'Romanya',
    RU: 'Rusya',
    SA: 'Suudi Arabistan',
    RS: 'Sırbistan',
    SG: 'Singapur',
    SK: 'Slovakya',
    SI: 'Slovenya',
    ZA: 'Güney Afrika',
    KR: 'Güney Kore',
    ES: 'İspanya',
    LK: 'Sri Lanka',
    SE: 'İsveç',
    CH: 'İsviçre',
    TW: 'Tayvan',
    TH: 'Tayland',
    TN: 'Tunus',
    TR: 'Türkiye',
    UA: 'Ukrayna',
    AE: 'Birleşik Arap Emirlikleri',
    GB: 'Birleşik Krallık',
    US: 'Amerika Birleşik Devletleri',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  pl: {
    AF: 'Afganistan',
    AL: 'Albania',
    DZ: 'Algieria',
    AR: 'Argentyna',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbejdżan',
    BH: 'Bahrajn',
    BD: 'Bangladesz',
    BY: 'Białoruś',
    BE: 'Belgia',
    BA: 'Bośnia i Hercegowina',
    BR: 'Brazylia',
    BG: 'Bułgaria',
    CA: 'Kanada',
    CL: 'Chile',
    CN: 'Chiny',
    CO: 'Kolumbia',
    HR: 'Chorwacja',
    CY: 'Cypr',
    CZ: 'Czechy',
    DK: 'Dania',
    EG: 'Egipt',
    EE: 'Estonia',
    FI: 'Finlandia',
    FR: 'Francja',
    GE: 'Gruzja',
    DE: 'Niemcy',
    GH: 'Ghana',
    GR: 'Grecja',
    HK: 'SRA Hongkong (Chiny)',
    HU: 'Węgry',
    IS: 'Islandia',
    IN: 'Indie',
    ID: 'Indonezja',
    IR: 'Iran',
    IQ: 'Irak',
    IE: 'Irlandia',
    IL: 'Izrael',
    IT: 'Włochy',
    JP: 'Japonia',
    JO: 'Jordania',
    KZ: 'Kazachstan',
    KE: 'Kenia',
    KW: 'Kuwejt',
    LV: 'Łotwa',
    LB: 'Liban',
    LT: 'Litwa',
    LU: 'Luksemburg',
    MY: 'Malezja',
    MT: 'Malta',
    MX: 'Meksyk',
    MD: 'Mołdawia',
    MA: 'Maroko',
    NL: 'Holandia',
    NZ: 'Nowa Zelandia',
    NG: 'Nigeria',
    MK: 'Macedonia Północna',
    NO: 'Norwegia',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Filipiny',
    PL: 'Polska',
    PT: 'Portugalia',
    QA: 'Katar',
    RO: 'Rumunia',
    RU: 'Rosja',
    SA: 'Arabia Saudyjska',
    RS: 'Serbia',
    SG: 'Singapur',
    SK: 'Słowacja',
    SI: 'Słowenia',
    ZA: 'Republika Południowej Afryki',
    KR: 'Korea Południowa',
    ES: 'Hiszpania',
    LK: 'Sri Lanka',
    SE: 'Szwecja',
    CH: 'Szwajcaria',
    TW: 'Tajwan',
    TH: 'Tajlandia',
    TN: 'Tunezja',
    TR: 'Turcja',
    UA: 'Ukraina',
    AE: 'Zjednoczone Emiraty Arabskie',
    GB: 'Wielka Brytania',
    US: 'Stany Zjednoczone',
    UY: 'Urugwaj',
    VE: 'Wenezuela',
    VN: 'Wietnam',
  },
  es: {
    AF: 'Afganistán',
    AL: 'Albania',
    DZ: 'Argelia',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaiyán',
    BH: 'Baréin',
    BD: 'Bangladés',
    BY: 'Bielorrusia',
    BE: 'Bélgica',
    BA: 'Bosnia y Herzegovina',
    BR: 'Brasil',
    BG: 'Bulgaria',
    CA: 'Canadá',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    HR: 'Croacia',
    CY: 'Chipre',
    CZ: 'Chequia',
    DK: 'Dinamarca',
    EG: 'Egipto',
    EE: 'Estonia',
    FI: 'Finlandia',
    FR: 'Francia',
    GE: 'Georgia',
    DE: 'Alemania',
    GH: 'Ghana',
    GR: 'Grecia',
    HK: 'RAE de Hong Kong (China)',
    HU: 'Hungría',
    IS: 'Islandia',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Irán',
    IQ: 'Irak',
    IE: 'Irlanda',
    IL: 'Israel',
    IT: 'Italia',
    JP: 'Japón',
    JO: 'Jordania',
    KZ: 'Kazajistán',
    KE: 'Kenia',
    KW: 'Kuwait',
    LV: 'Letonia',
    LB: 'Líbano',
    LT: 'Lituania',
    LU: 'Luxemburgo',
    MY: 'Malasia',
    MT: 'Malta',
    MX: 'México',
    MD: 'Moldavia',
    MA: 'Marruecos',
    NL: 'Países Bajos',
    NZ: 'Nueva Zelanda',
    NG: 'Nigeria',
    MK: 'Macedonia del Norte',
    NO: 'Noruega',
    OM: 'Omán',
    PK: 'Pakistán',
    PH: 'Filipinas',
    PL: 'Polonia',
    PT: 'Portugal',
    QA: 'Catar',
    RO: 'Rumanía',
    RU: 'Rusia',
    SA: 'Arabia Saudí',
    RS: 'Serbia',
    SG: 'Singapur',
    SK: 'Eslovaquia',
    SI: 'Eslovenia',
    ZA: 'Sudáfrica',
    KR: 'Corea del Sur',
    ES: 'España',
    LK: 'Sri Lanka',
    SE: 'Suecia',
    CH: 'Suiza',
    TW: 'Taiwán',
    TH: 'Tailandia',
    TN: 'Túnez',
    TR: 'Turquía',
    UA: 'Ucrania',
    AE: 'Emiratos Árabes Unidos',
    GB: 'Reino Unido',
    US: 'Estados Unidos',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  fr: {
    AF: 'Afghanistan',
    AL: 'Albanie',
    DZ: 'Algérie',
    AR: 'Argentine',
    AM: 'Arménie',
    AU: 'Australie',
    AT: 'Autriche',
    AZ: 'Azerbaïdjan',
    BH: 'Bahreïn',
    BD: 'Bangladesh',
    BY: 'Biélorussie',
    BE: 'Belgique',
    BA: 'Bosnie-Herzégovine',
    BR: 'Brésil',
    BG: 'Bulgarie',
    CA: 'Canada',
    CL: 'Chili',
    CN: 'Chine',
    CO: 'Colombie',
    HR: 'Croatie',
    CY: 'Chypre',
    CZ: 'Tchéquie',
    DK: 'Danemark',
    EG: 'Égypte',
    EE: 'Estonie',
    FI: 'Finlande',
    FR: 'France',
    GE: 'Géorgie',
    DE: 'Allemagne',
    GH: 'Ghana',
    GR: 'Grèce',
    HK: 'R.A.S. chinoise de Hong Kong',
    HU: 'Hongrie',
    IS: 'Islande',
    IN: 'Inde',
    ID: 'Indonésie',
    IR: 'Iran',
    IQ: 'Irak',
    IE: 'Irlande',
    IL: 'Israël',
    IT: 'Italie',
    JP: 'Japon',
    JO: 'Jordanie',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KW: 'Koweït',
    LV: 'Lettonie',
    LB: 'Liban',
    LT: 'Lituanie',
    LU: 'Luxembourg',
    MY: 'Malaisie',
    MT: 'Malte',
    MX: 'Mexique',
    MD: 'Moldavie',
    MA: 'Maroc',
    NL: 'Pays-Bas',
    NZ: 'Nouvelle-Zélande',
    NG: 'Nigeria',
    MK: 'Macédoine du Nord',
    NO: 'Norvège',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Philippines',
    PL: 'Pologne',
    PT: 'Portugal',
    QA: 'Qatar',
    RO: 'Roumanie',
    RU: 'Russie',
    SA: 'Arabie saoudite',
    RS: 'Serbie',
    SG: 'Singapour',
    SK: 'Slovaquie',
    SI: 'Slovénie',
    ZA: 'Afrique du Sud',
    KR: 'Corée du Sud',
    ES: 'Espagne',
    LK: 'Sri Lanka',
    SE: 'Suède',
    CH: 'Suisse',
    TW: 'Taïwan',
    TH: 'Thaïlande',
    TN: 'Tunisie',
    TR: 'Turquie',
    UA: 'Ukraine',
    AE: 'Émirats arabes unis',
    GB: 'Royaume-Uni',
    US: 'États-Unis',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Viêt Nam',
  },
  it: {
    AF: 'Afghanistan',
    AL: 'Albania',
    DZ: 'Algeria',
    AR: 'Argentina',
    AM: 'Armenia',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaigian',
    BH: 'Bahrein',
    BD: 'Bangladesh',
    BY: 'Bielorussia',
    BE: 'Belgio',
    BA: 'Bosnia ed Erzegovina',
    BR: 'Brasile',
    BG: 'Bulgaria',
    CA: 'Canada',
    CL: 'Cile',
    CN: 'Cina',
    CO: 'Colombia',
    HR: 'Croazia',
    CY: 'Cipro',
    CZ: 'Cechia',
    DK: 'Danimarca',
    EG: 'Egitto',
    EE: 'Estonia',
    FI: 'Finlandia',
    FR: 'Francia',
    GE: 'Georgia',
    DE: 'Germania',
    GH: 'Ghana',
    GR: 'Grecia',
    HK: 'RAS di Hong Kong',
    HU: 'Ungheria',
    IS: 'Islanda',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Irlanda',
    IL: 'Israele',
    IT: 'Italia',
    JP: 'Giappone',
    JO: 'Giordania',
    KZ: 'Kazakistan',
    KE: 'Kenya',
    KW: 'Kuwait',
    LV: 'Lettonia',
    LB: 'Libano',
    LT: 'Lituania',
    LU: 'Lussemburgo',
    MY: 'Malaysia',
    MT: 'Malta',
    MX: 'Messico',
    MD: 'Moldavia',
    MA: 'Marocco',
    NL: 'Paesi Bassi',
    NZ: 'Nuova Zelanda',
    NG: 'Nigeria',
    MK: 'Macedonia del Nord',
    NO: 'Norvegia',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Filippine',
    PL: 'Polonia',
    PT: 'Portogallo',
    QA: 'Qatar',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Arabia Saudita',
    RS: 'Serbia',
    SG: 'Singapore',
    SK: 'Slovacchia',
    SI: 'Slovenia',
    ZA: 'Sudafrica',
    KR: 'Corea del Sud',
    ES: 'Spagna',
    LK: 'Sri Lanka',
    SE: 'Svezia',
    CH: 'Svizzera',
    TW: 'Taiwan',
    TH: 'Thailandia',
    TN: 'Tunisia',
    TR: 'Turchia',
    UA: 'Ucraina',
    AE: 'Emirati Arabi Uniti',
    GB: 'Regno Unito',
    US: 'Stati Uniti',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
  de: {
    AF: 'Afghanistan',
    AL: 'Albanien',
    DZ: 'Algerien',
    AR: 'Argentinien',
    AM: 'Armenien',
    AU: 'Australien',
    AT: 'Österreich',
    AZ: 'Aserbaidschan',
    BH: 'Bahrain',
    BD: 'Bangladesch',
    BY: 'Belarus',
    BE: 'Belgien',
    BA: 'Bosnien und Herzegowina',
    BR: 'Brasilien',
    BG: 'Bulgarien',
    CA: 'Kanada',
    CL: 'Chile',
    CN: 'China',
    CO: 'Kolumbien',
    HR: 'Kroatien',
    CY: 'Zypern',
    CZ: 'Tschechien',
    DK: 'Dänemark',
    EG: 'Ägypten',
    EE: 'Estland',
    FI: 'Finnland',
    FR: 'Frankreich',
    GE: 'Georgien',
    DE: 'Deutschland',
    GH: 'Ghana',
    GR: 'Griechenland',
    HK: 'Sonderverwaltungsregion Hongkong',
    HU: 'Ungarn',
    IS: 'Island',
    IN: 'Indien',
    ID: 'Indonesien',
    IR: 'Iran',
    IQ: 'Irak',
    IE: 'Irland',
    IL: 'Israel',
    IT: 'Italien',
    JP: 'Japan',
    JO: 'Jordanien',
    KZ: 'Kasachstan',
    KE: 'Kenia',
    KW: 'Kuwait',
    LV: 'Lettland',
    LB: 'Libanon',
    LT: 'Litauen',
    LU: 'Luxemburg',
    MY: 'Malaysia',
    MT: 'Malta',
    MX: 'Mexiko',
    MD: 'Republik Moldau',
    MA: 'Marokko',
    NL: 'Niederlande',
    NZ: 'Neuseeland',
    NG: 'Nigeria',
    MK: 'Nordmazedonien',
    NO: 'Norwegen',
    OM: 'Oman',
    PK: 'Pakistan',
    PH: 'Philippinen',
    PL: 'Polen',
    PT: 'Portugal',
    QA: 'Katar',
    RO: 'Rumänien',
    RU: 'Russland',
    SA: 'Saudi-Arabien',
    RS: 'Serbien',
    SG: 'Singapur',
    SK: 'Slowakei',
    SI: 'Slowenien',
    ZA: 'Südafrika',
    KR: 'Südkorea',
    ES: 'Spanien',
    LK: 'Sri Lanka',
    SE: 'Schweden',
    CH: 'Schweiz',
    TW: 'Taiwan',
    TH: 'Thailand',
    TN: 'Tunesien',
    TR: 'Türkei',
    UA: 'Ukraine',
    AE: 'Vereinigte Arabische Emirate',
    GB: 'Vereinigtes Königreich',
    US: 'Vereinigte Staaten',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
  },
};

/** The country's name in the given language, falling back to whatever the
 * calling-code table carries (English) for anything unlisted. */
export function localizedCountryName(iso2: string, language: string, fallback: string): string {
  const forLanguage = COUNTRY_NAMES[language as SupportedLanguage];
  return forLanguage?.[iso2] ?? fallback;
}
